microservice:
   order-service:
        endpoints:
            endpoint:
                uri: http://ORDER-SERVICE/order/bookOrder
   payment-service:
        endpoints:
            endpoint:
                uri: http://PAYMENT-SERVICE/payment/doPayment                
       
